version: '3.8'  
services:  
    db:  
        image: postgres:latest  
        environment:  
            POSTGRES_DB: postgres  
            POSTGRES_USER: postgres  
            POSTGRES_PASSWORD: kalimid 
        ports:  
            - '5432:5432'
    app:  
        build:
            context: .  
            dockerfile: Dockerfile
        image: ilnur057/wbot:latest
        ports:  
            - '8080:8080'
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: kalimid
            SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
        depends_on:  
            - db